client_cache_capacity: 512
client_cache_ttl: 57
client_cacheable_methods:
- POST
- GET
client_cacheable_status_codes:
- 200
- 201
client_exponential_backoff_max: 60
client_num_retries: 2
client_reraise_from_retry_error: true
client_retry_status_codes:
- 408
- 429
- 500
- 502
- 503
- 504
max_concurrent_downloads: 5
max_wait_time: 3600
part_size: 16777216
per_request_jitter: 0.0
retry_after_applicable_for_num_requests: 1
wkvs_api_url: https://127.0.0.1
